# -*- coding: utf-8 -*-
"""Entregable 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIS7Cw3zo2gWvgmLlf2BRf-8DmDmfKrg
"""

import pandas as pd
import numpy as np

datos = {
    "Muestra": ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "M10"],
    "Lamivudina_tabletas": ["104,9%", "101,2%", "102,2%", "100,2%", "102,6%", "103,2%", "101,2%", "104,9%", "104,1%", "102,6%"],
    "Epivir_A": ["98,5%", "100,3%", "99,1%", "100,9%", "100,8%", "99,1%", "101,5%", "101,0%", "104,2%", "100,3%"],
    "Epivir_B": ["101,8%", "98,6%", "104,1%", "98,6%", "101,7%", "104,2%", "101,8%", "98,5%", "104,2%", "98,6%"]
}

df = pd.DataFrame(datos)

def convertir_porcentaje(valor):
    return float(valor.replace(",", ".").replace("%", ""))

columnas_medicamentos = ["Lamivudina_tabletas", "Epivir_A", "Epivir_B"]
for col in columnas_medicamentos:
    df[col] = df[col].apply(convertir_porcentaje)

df.head(10)

# @title Lamivudina_tabletas

from matplotlib import pyplot as plt
df['Lamivudina_tabletas'].plot(kind='line', figsize=(8, 4), title='Lamivudina_tabletas')
plt.gca().spines[['top', 'right']].set_visible(False)

promedios = df[["Lamivudina_tabletas", "Epivir_A", "Epivir_B"]].mean()
desviaciones = df[["Lamivudina_tabletas", "Epivir_A", "Epivir_B"]].std()
# Mostrar resultados
print("Promedios:")
print(promedios, "\n")

print("Desviaciones estándar:")
print(desviaciones, "\n")

diff_L_vs_A = np.abs(df["Lamivudina_tabletas"] - df["Epivir_A"]).mean()
diff_L_vs_B = np.abs(df["Lamivudina_tabletas"] - df["Epivir_B"]).mean()

print("Diferencia promedio absoluta:")
print(f"Lamivudina vs Epivir_A: {diff_L_vs_A:.2f}")
print(f"Lamivudina vs Epivir_B: {diff_L_vs_B:.2f}\n")

cv = (desviaciones / promedios) * 100
print("Coeficiente de variación (CV %):")
print(cv, "\n")

k = 2.4  # constante para n=10
M = 100  # valor nominal
AV = abs(M - promedios) + k * desviaciones
print("AV (Acceptance Value):")
print(AV)

if all(AV < 15):
    print("✅ Todas las formulaciones cumplen con el valor de aceptación (AV < 15).")
else:
    print("❌ Al menos una formulación no cumple con el valor de aceptación.")